### PR TITLE
ESBuild externals (ESM to CJS bundle)

### PR DESCRIPTION
**Pull request by danielweck**
Fixes https://github.com/weiran-zsd/eslint-plugin-node/issues/9

### CODE REVIEW

**Comment by aladdin-add** [comment]
hi, thanks for the PR! 👍 

I'm seeing it has only 1 dep: `builtins`- (refs: https://github.com/wooorm/import-meta-resolve/blob/4dc54e351c2eec50cd769933fba0b8d1f2377dc3/package.json#L32).  are the other 2 deps really needed?

**Comment by danielweck** [comment]
Ah, transient dependencies ... let me check :)

**Comment by danielweck** [comment]
> Ah, transient dependencies ... let me check :)

Fixed, thank you for spotting this 👍

**Review by aladdin-add — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
